Allow granular progress updates & associated changes
scijava/scijava pull request #213
Opened 2024-05-03 20:05 UTC by gselzer

This PR refactors the scijava-progress module API, for the goals of simplicity and better progress reporting within dependencies, and should be squeaked in before the 1.0.0 release.

Important changes:
* Progress stages have been done away with, with `Task`s instead having a single tracker of `elements`, discrete packets of progress updates. The number of elements a Task will have is dictated during `Progress.defineTotal`, meaning we no longer need the `Progress.setStageMax` method.
* The progress of Op dependencies was previously limited to a boolean value, which is not helpful for "wrapper Ops", where progress updates are most important in dependency subtasks. Dependency progress updates are now passed along to *every* parent using a new method `Task.parent()`, meaning that if an Op dependency has a dependency itself that issues an update, `ProgressListeners` tuned to its parent and grandparent will be notified as well. To prevent an overwhelming amount of dependencies from flooding the SciJava Ops Legacy progress listener only posts updates for tasks with no parent.
  * To enable progress updates from Op dependencies, you must add the `"progress.TRACK"` hint (i.e. `org.scijava.ops.engine.BaseOpHints.Progress.TRACK`), **and** use `Progress.defineTotal(x, y)`, where `x` is a long defining the number of elements in the *parent* Op and `y` is the total number of reporting dependency executions. E.g.
```java
public class ParentOp implements Function<X, Y> {
  @OpDependency(name="foo.bar", hints={"progress.TRACK"})
  Function<X, Y> foo;
  @OpDependency(name="baz.bar", hints={"progress.TRACK"})
  Function<X, Y> baz;

  @Override
  public Y apply(X in) {
    Progress.defineTotal(0, 3);
    out1 = foo.apply(in);
    out2 = foo.apply(in);
    out3 = baz.apply(in);
    return out3;
  }
}
```
* Two of the most intensive Ops, `coloc.saca.heatmapZScore` and `deconvolve.richardsonLucy`, now report progress.

As we are approaching the initial release, we should consider the API - I know @ctrueden wanted to do an API review, so I'm pinging his review as motivation to review the scijava-progress public API. I'm also asking for @elevans' opinion as an Ops developer/user - if you'd like to try your hand at adding progress to fully test the API, I'd appreciate it, but if you're busy no worries.

Points of Discussion:

* Can we make it easier for progress listeners to receive updates only about top-level Ops (i.e. not Op dependencies)?
* It would be slick to add progress updates to `LoopBuilder` constructs such that pixel-wise Ops always report progress when lifted to image level, however this anecdotally incurs very poor performance due to the constant multithreaded updates to the `AtomicLong` tracking progress. @tpietzsch is there anything that we could do, here or upstream in ImgLib2, to enable progress reporting? Potentially one update per chunk would be awesome - would it be possible to add API to report chunk size, for example?

TODO:

* [ ] Update documentation
* [ ] Add progress to any more Ops?

2024-05-06 14:00 UTC, gselzer reviewed
Here are my suggestions! Thanks @gselzer for doing this work!

2024-05-06 15:17 UTC, gselzer commented on scijava-progress/src/main/java/org/scijava/progress/Progress.java
> +		public void define(final long elements, final long subTasks) {
Fixed!

2024-05-06 17:12 UTC, gselzer commented on scijava-progress/src/main/java/org/scijava/progress/Task.java
> +	 * @param elements the number of discrete "elements" in the computation
Fixed

2024-05-06 17:13 UTC, gselzer commented on scijava-progress/src/main/java/org/scijava/progress/Task.java
> +		this.tasks = subTasks + (elements == 0 ? 0 : 1);
Folded!

2024-05-06 19:33 UTC, gselzer commented on scijava-progress/src/main/java/org/scijava/progress/Task.java
> +		}
Fixed!

2024-05-06 20:36 UTC, gselzer commented on scijava-progress/src/main/java/org/scijava/progress/Task.java
> +	public Task parent() {
Changed!

2024-05-06 20:37 UTC, gselzer commented on scijava-ops-legacy/src/main/java/org/scijava/legacy/service/DefaultOpEnvironmentService.java
> +			if (task.parent() != null) return;
Added a new method `task.isSubTask` so we don't have to expose the parent for this use case.

2024-05-06 21:20 UTC, gselzer commented on scijava-ops-tutorial/src/main/java/org/scijava/ops/tutorial/ReportingProgress.java
> +		Progress.defineTotal(numPrimes, 0);
Much better now!

2024-05-09 18:03 UTC, elevans requested changes
@gselzer Nice PR! Ty for this work adding progress updates to SciJava Ops. This is much appreciated for those long Ops. There a few documentation changes I'd like to see before we merge this into `main`. I also have some open questions that I'd like to get your thoughts on:

1. The progress bar/feedback only really works with Fiji correct? Is there something we can do for users that are using SciJava Ops from Python or some other non-Fiji entry-point?
2. The `create.kernelDiffraction` Op that creates the PSF for deconvolution takes a little bit of time (not much but its detectable). That might be another good Op to add progress to.
3. How does this progress mechanism work with external libraries?

2024-05-09 18:03 UTC, elevans commented on docs/ops/doc/WritingYourOwnOpPackage.md
> +
Can you discuss what, if any, performance hit a developer might expect with `Progress`? Maybe a little section on ideal use versus what a **bad** use of `Progress` looks like. I don't think we need to go crazy, but just a flavor.

2024-05-09 18:53 UTC, gselzer commented
@elevans thanks for the feedback!

>     1. The progress bar/feedback only really works with Fiji correct? Is there something we can do for users that are using SciJava Ops from Python or some other non-Fiji entry-point?

There is nothing Fiji-specific about scijava-progress. e.g. Python users could just write a new `ProgressListener` implementation and add it as a global listener, and it would receive progress updates in the same way that the Fiji progress bar does.

...this makes me think that we should probably do away with the `ProgressListener` interface, and operate on `Consumer<Task>`s - it would be a little less code for us.

>     2. The `create.kernelDiffraction` Op that creates the PSF for deconvolution takes a little bit of time (not much but its detectable). That might be another good Op to add progress to.

Sure! Do you want to try it?

>     3. How does this progress mechanism work with external libraries?

I'm not really sure what you mean by this. If you're talking about progress updates of libraries that don't depend upon scijava-progress, all Ops record binary progress updates. This means that when you invoke the Op, all `ProgressListener`s listening to that Op will get a ping that the invocation is 0% complete. Then all computation happens, and once that finishes all `ProgressListener`s will get a ping that the invocation is 100% complete. In practice, you'll just see that it's running, but you won't get granular updates until you depend on scijava-progress and do the updates described in the documentation. I don't know of a way to do any better.

If you're talking about how external libraries can register their own `ProgressListener`s, they'll naturally have to depend upon scijava-progress and create their own `ProgressListener`s.

Does that help?

2024-05-09 18:56 UTC, gselzer commented on docs/ops/doc/WritingYourOwnOpPackage.md
> +By adding the `scijava-progress` module, your Op can define and update its progress, providing user value for long-running Ops. To add progress to your Op, you must add the following steps to your Op
They'd receive no feedback, unless they write their own `ProgressListener` and register it within the `Progress` class.

Naively speaking, I'd assume any scijava-ops-python component could harness [tqdm](https://tqdm.github.io/) to record progress updates, for example.

2024-05-09 19:21 UTC, gselzer commented on docs/ops/doc/WritingYourOwnOpPackage.md
> +* Replace `Progress.defineTotal(long elements)` with `Progress.defineTotal(long elements, long subTasks)`, where `subTasks` is the **total** number of times you will invoke Op dependencies annotated
Dependencies do *not* need to define their progress for updates in the dependent Op. If they do not define progress, they will only update the parent progress upon their completion, though.

For example, suppose you have 2 elements worth of updates in your Op, and in between them your Op calls a dependency, which under the hood has 10 elements:
* If that Op reports its progress i.e. calls `Progress.upate()`, the dependent Op's progress will go `0.0` -> `0.33` -> `0.36` -> `0.39` -> ... -> `0.63` -> `0.66` -> `1.0`
* If that Op **does not** report its progress the dependent Op's progress will go `0.0` -> `0.33` -> `0.66` -> `1.0`

2024-05-09 21:01 UTC, elevans commented
Awesome thanks @gselzer for the explanations. I'm happy that you've addressed all my comments. Ready to merge!

2024-05-09 21:03 UTC, merged